name: Deploy Static Website

on:
  push:
    branches:
      - main  # or your preferred branch name

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload static files
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'  # Your root folder (or change to your static folder like ./site or ./public)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
